Add startup triggers as a utility for other jobs
cfpb/jenkins-automation pull request #115
Opened 2017-10-19 18:34 UTC by champain

This reusable startup trigger should fold in with any DSL job except for pipelines easily.

2017-10-19 18:37 UTC, acrewdson requested changes
one small change, otherwise looks good to me

2017-10-19 18:37 UTC, acrewdson commented on docs/examples.md
> +mport jenkins.automation.builders.BaseJobBuilder
`import`

2017-10-19 19:17 UTC, champain commented on docs/examples.md
> +mport jenkins.automation.builders.BaseJobBuilder
Good catch

2017-10-19 19:21 UTC, OrlandoSoto approved these changes
👍

2017-10-19 19:33 UTC, champain commented
@acrewdson changes submited

2017-10-19 19:39 UTC, acrewdson approved these changes

2017-10-19 20:22 UTC, champain commented
Merge when ready on this one. Gonna give a little time for either @marcesher or @imuchnik to look at this.

2017-10-20 14:33 UTC, imuchnik approved these changes
LGTM

2017-10-20 14:37 UTC, acrewdson commented
@champain you want to merge when ready?

2017-10-20 14:44 UTC, merged